
-- Supabase Schema for Farah Cakes (Heaven Bakery Engine)
-- Run this in your Supabase SQL Editor (app.supabase.com) to set up the necessary tables.

-- 1. Sites Table
CREATE TABLE IF NOT EXISTS sites (
    id TEXT PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    logo TEXT,
    phone TEXT,
    "adminUser" TEXT NOT NULL,
    "adminPass" TEXT NOT NULL,
    "adminSurname" TEXT,
    "themeColor" TEXT,
    tagline TEXT,
    "maxItems" INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Cakes Table
CREATE TABLE IF NOT EXISTS cakes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    "imageUrl" TEXT,
    category TEXT,
    "siteId" TEXT REFERENCES sites(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Coupons Table
CREATE TABLE IF NOT EXISTS coupons (
    code TEXT NOT NULL,
    "discountPercent" NUMERIC NOT NULL DEFAULT 0,
    "siteId" TEXT REFERENCES sites(id) ON DELETE CASCADE,
    PRIMARY KEY (code, "siteId"),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    "siteId" TEXT REFERENCES sites(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
